
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covidmyapp-deployment
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: localhost:32000/cassandra-test:registry
        ports:
        - containerPort: 443